-- begin BOOKSHOP_CART
alter table BOOKSHOP_CART add constraint FK_BOOKSHOP_CART_ON_BOOK foreign key (BOOK_ID) references BOOKSHOP_BOOK(ID)^
alter table BOOKSHOP_CART add constraint FK_BOOKSHOP_CART_ON_CUSTOMER foreign key (CUSTOMER_ID) references BOOKSHOP_CUSTOMER(ID)^
alter table BOOKSHOP_CART add constraint FK_BOOKSHOP_CART_ON_ORDER foreign key (ORDER_ID) references BOOKSHOP_ORDER(ID)^
create index IDX_BOOKSHOP_CART_ON_BOOK on BOOKSHOP_CART (BOOK_ID)^
create index IDX_BOOKSHOP_CART_ON_CUSTOMER on BOOKSHOP_CART (CUSTOMER_ID)^
create index IDX_BOOKSHOP_CART_ON_ORDER on BOOKSHOP_CART (ORDER_ID)^
-- end BOOKSHOP_CART
-- begin BOOKSHOP_CUSTOMER
create unique index IDX_BOOKSHOP_CUSTOMER_UNIQ_EMAIL on BOOKSHOP_CUSTOMER (EMAIL)^
create index IDX_BOOKSHOP_CUSTOMER_SURNAME on BOOKSHOP_CUSTOMER (SURNAME)^
-- end BOOKSHOP_CUSTOMER
-- begin BOOKSHOP_ORDER
alter table BOOKSHOP_ORDER add constraint FK_BOOKSHOP_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references BOOKSHOP_CUSTOMER(ID)^
create index IDX_BOOKSHOP_ORDER_ON_CUSTOMER on BOOKSHOP_ORDER (CUSTOMER_ID)^
-- end BOOKSHOP_ORDER
-- begin BOOKSHOP_BOOK
create index IDX_BOOKSHOP_BOOK_NAME on BOOKSHOP_BOOK (BOOK_NAME)^
-- end BOOKSHOP_BOOK
