alter table PHOTOSALON_ORDER add constraint FK_PHOTOSALON_ORDER_ON_CUSTOMER_INFO foreign key (CUSTOMER_INFO_ID) references PHOTOSALON_CUSTOMER(ID);
create index IDX_PHOTOSALON_ORDER_ON_CUSTOMER_INFO on PHOTOSALON_ORDER (CUSTOMER_INFO_ID);
