window._tx=function(e){e.lib=function(b){function p(){try{var a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(C){a=!1}}a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);return a}b.txqpid=null;b.foadh=null;b.cdh=null;b.ddh=".hybrid.ai";b.aldhs=[".astraone.io",".adhello.pl"];b.ppb=!1;var l=function(a){a.stringify=function(c){return window.JSON&&window.JSON.stringify?window.JSON.stringify(c):a.encode(c)};a.parse=function(c){return window.JSON&&
window.JSON.parse?window.JSON.parse(c):a.decode(c)};a.encode=function(a){switch(typeof a){case "string":return"'"+a+"'";case "number":return isFinite(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";var c=[];if("[object Array]"===Object.prototype.toString.apply(a)){for(var d=0;d<a.length;d++)c[d]=this.encode(a[d])||"null";return"["+c.join(",")+"]"}for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)){var b=this.encode(a[d]);b&&c.push("'"+d+"':"+b)}return"{"+
c.join(",")+"}"}};a.decode=function(a){return null!==a&&"string"===typeof a&&/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,"@").replace(/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?(new Function("return "+a))():null};return a}(e.JSON||{}),t=function(){var a={};try{location&&location.href&&4<location.href.length&&1E3>location.href.length&&(a.Url=location.href),document&&document.referrer&&4<document.referrer.length&&
1E3>document.referrer.length&&(a.Referrer=document.referrer),a.Language=navigator?navigator.language||navigator.browserLanguage:"",screen&&Number(screen.width)===screen.width&&0===screen.width%1&&Number(screen.height)===screen.height&&0===screen.height%1&&0<screen.width&&2147483647>screen.width&&0<screen.height&&2147483647>screen.height&&(a.ScreenWidth=screen.width,a.ScreenHeight=screen.height),a.TimezoneOffset=(new Date).getTimezoneOffset()/60}catch(c){}return a},u=function(a,c,b){a.addEventListener?
a.addEventListener(c,b,!1):a.attachEvent&&a.attachEvent("on"+c,b)},w=function(a,c){var b=document.createElement("script");b.type="text/javascript";b.async=c;b.src=a;(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(b)},y=function(a){if(window.Image)var c=new Image;else document&&(c=document.createElement("img"),c.width=1,c.height=1);if(c)c.onload=c.onerror=function(){c.onload=null;c.onerror=null},c.src=a;else{var b=p();b&&(b.open("GET",a,!0),b.send(null))}},
z=function(){var a={apl:null,cs:"",pcs:[],vcs:[]},c=window.__tcfapi;if(!c)try{for(var b,d=window;d;){try{if(d.frames.__tcfapiLocator){b=d;break}}catch(g){}if(d===window.top)break;d=d.parent}if(b){var f={};c=function(a,c,d,e){var g=Math.random()+"";a={__tcfapiCall:{command:a,parameter:e,version:c,callId:g}};f[g]=d;b.postMessage(a,"*")};u(window,"message",function(a){a="string"===typeof a.data?l.parse(a.data):a.data;a.__tcfapiReturn&&(a=a.__tcfapiReturn,"function"===typeof f[a.callId]&&(f[a.callId](a.returnValue,
a.success),delete f[a.callId]))},!1)}}catch(g){}if(c)try{d=function(b,c){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.tcString;if(b.purpose&&b.purpose.consents)for(var d in b.purpose.consents)b.purpose.consents[d]&&-1===a.pcs.indexOf(d)&&a.pcs.push(d);if(b.vendor&&b.vendor.consents)for(var g in b.vendor.consents)b.vendor.consents[g]&&-1===a.vcs.indexOf(g)&&a.vcs.push(g)}},c("getTCData",2,d),c("getTCData",1,d)}catch(g){}c=window.__cmp;if(!c)try{var e;for(d=window;!e;){try{d.frames.__cmpLocator&&(e=
d)}catch(g){}if(d===window.top)break;d=d.parent}if(e){var h={};c=function(a,b,c){var d=Math.random()+"";a={__cmpCall:{command:a,parameter:b,callId:d}};h[d]=c;e.postMessage(a,"*")};u(window,"message",function(a){a="string"===typeof a.data?l.parse(a.data):a.data;a.__cmpReturn&&(a=a.__cmpReturn,h[a.callId](a.returnValue,a.success),delete h[a.callId])},!1)}}catch(g){}if(c)try{d=function(b,c){if(b){a.apl=a.apl||b.gdprApplies;a.cs=a.cs||b.consentData||b.metadata||"";if(b.purposeConsents)for(var d in b.purposeConsents)b.purposeConsents[d]&&
-1===a.pcs.indexOf(d)&&a.pcs.push(d);if(b.vendorConsents)for(var e in b.vendorConsents)b.vendorConsents[e]&&-1===a.vcs.indexOf(e)&&a.vcs.push(e)}},c("getConsentData",null,d),c("getVendorConsents",null,d)}catch(g){}return a},m=function(a){return"foadh="+encodeURIComponent(a||"")},n=function(){var a=z();return"gapl="+(null!=a.apl?a.apl?"1":"0":"")+"&cs="+a.cs+"&pcs="+a.pcs.join("_")+"&vcs="+a.vcs.join("_")},x=function(){var a=document.getElementsByTagName("script");if(a)for(var c=0;c<a.length;c++)for(var e=
a[c].src,d=0;d<b.aldhs.length;d++){var f=b.aldhs[d];if(-1<e.indexOf(f)&&(-1<e.indexOf("txsp.js")||-1<e.indexOf("advertiser.js")))return f}return b.ddh},q=function(){return"https://dss"+(b.cdh||x())+"/"},r=function(a){b.ppb?window.setTimeout(function(){r(a)},1E3):(b.ppb=!0,y(a),window.setTimeout(function(){b.ppb=!1},1E3))},v=function(a,b,e,d,f,k,h,g){a="Pixel/Track2?pid="+(a||"")+"&evt="+encodeURIComponent(b||"")+"&cost="+encodeURIComponent(e||"")+"&text="+encodeURIComponent(d||"")+"&ltm="+(k||!1)+
"&cnt="+(f||"")+"&url="+encodeURIComponent(h.Url||"")+"&rf="+encodeURIComponent(h.Referrer||"")+"&lng="+(h.Language||"")+"&tz="+(h.TimezoneOffset||"")+"&sw="+(h.ScreenWidth||"")+"&sh="+(h.ScreenHeight||"")+"&"+m(g)+"&"+n()+"&r=";r(q()+a)},A=function(a,b,e,d,f){a="Pixel/DynamicTrack?pid="+(a||"")+"&evt="+encodeURIComponent(b||"")+"&cnt="+encodeURIComponent(e||"")+"&url="+encodeURIComponent(d.Url||"")+"&rf="+encodeURIComponent(d.Referrer||"")+"&lng="+(d.Language||"")+"&tz="+(d.TimezoneOffset||"")+"&sw="+
(d.ScreenWidth||"")+"&sh="+(d.ScreenHeight||"")+"&"+m(f)+"&"+n()+"&r=";r(q()+a)},B=function(a,b,e,d,f,k){a="Pixel/Identify2?pid="+(a||"")+"&cstid="+(b||"")+"&icnt="+(e||"")+"&ucnt="+(d||"")+"&url="+encodeURIComponent(f.Url||"")+"&rf="+encodeURIComponent(f.Referrer||"")+"&lng="+(f.Language||"")+"&tz="+(f.TimezoneOffset||"")+"&sw="+(f.ScreenWidth||"")+"&sh="+(f.ScreenHeight||"")+"&"+m(k)+"&"+n()+"&r=";r(q()+a)};b.txqhnd=function(a){if(a&&"string"===typeof a[0]){var c=a[0].toLowerCase();if("createpixel"===
c)"string"==typeof a[1]&&(b.txqpid=a[1],a[2]&&(b.foadh=1),window.setTimeout(function(){var a=m(b.foadh),c=n();w("https://dm.hybrid.ai/plgt.js?fbpid="+b.txqpid+"&"+a+"&"+c,!0)},2E3));else if("track"===c){if("string"===typeof a[1]){var e=a[1],d=null;try{a[2]&&(d=encodeURIComponent(l.stringify(a[2])))}catch(h){}var f=t();"pageview"===e.toLowerCase()?(v(b.txqpid,e,null,null,d,!1,f,b.foadh),a=m(b.foadh),c=n(),w(q()+"Pixel/TrackTp?pid="+(b.txqpid||"")+"&"+a+"&"+c,!0),window.setTimeout(function(){v(b.txqpid,
e,null,null,d,!0,f,b.foadh)},15E3)):v(b.txqpid,e,a[3],a[4],d,!1,f,b.foadh)}}else if("track_d"===c){if("string"===typeof a[1]&&"string"===typeof a[2]){c=a[1];a=a[2];var k=t();A(b.txqpid,c,a,k,b.foadh)}}else if("identify"===c&&"string"===typeof a[1]){k=c=null;try{a[2]&&(c=encodeURIComponent(l.stringify(a[2]))),a[3]&&(k=encodeURIComponent(l.stringify(a[3])))}catch(h){}B(b.txqpid,a[1],c,k,t(),b.foadh)}}};b.txq=function(a){this.push(a)};b.txq.prototype.push=function(a){b.txqhnd(a)};b.txqi=function(){window._txq=
window._txq||[];if(window._txq)for(var a in window._txq)window._txq.hasOwnProperty(a)&&b.txqhnd(window._txq[a]);"complete"==document.readyState?window._txq=new b.txq(window._txq):u(document,"readystatechange",function(){window._txq=new b.txq(window._txq)});b.cdh=x()};return b}(e.lib||{});e.lib.txqi();e.sendPixel=function(b){e.lib.txqhnd(["createPixel",b]);e.lib.txqhnd(["track","PageView"])};e.sendEvent=function(b,p){e.lib.txqhnd(["createPixel",b]);e.lib.txqhnd(["track",p])};e.sendProductView=function(b,
p,l){e.lib.txqhnd(["createPixel",b]);e.lib.txqhnd(["track","ViewContent",{content_type:"product",content_ids:[l]}])};e.MarkVisitor=function(){};e.sendAudience=function(){};e.sendAudienceTags=function(){};return e}(window._tx||{});
