alter table AIRTICKETBOOKING_ORDER add constraint FK_AIRTICKETBOOKING_ORDER_ON_PASSANGER foreign key (PASSANGER_ID) references AIRTICKETBOOKING_PASSANGER(ID);
alter table AIRTICKETBOOKING_ORDER add constraint FK_AIRTICKETBOOKING_ORDER_ON_TICKET foreign key (TICKET_ID) references AIRTICKETBOOKING_TICKET(ID);
create index IDX_AIRTICKETBOOKING_ORDER_ON_PASSANGER on AIRTICKETBOOKING_ORDER (PASSANGER_ID);
create index IDX_AIRTICKETBOOKING_ORDER_ON_TICKET on AIRTICKETBOOKING_ORDER (TICKET_ID);
