-- begin AIRTICKETBOOKING_TICKET
create unique index IDX_AIRTICKETBOOKING_TICKET_UNIQ_TICKET_ID on AIRTICKETBOOKING_TICKET (TICKET_ID)^
-- end AIRTICKETBOOKING_TICKET
-- begin AIRTICKETBOOKING_ORDER
alter table AIRTICKETBOOKING_ORDER add constraint FK_AIRTICKETBOOKING_ORDER_ON_PASSANGER foreign key (PASSANGER_ID) references AIRTICKETBOOKING_PASSANGER(ID)^
alter table AIRTICKETBOOKING_ORDER add constraint FK_AIRTICKETBOOKING_ORDER_ON_TICKET foreign key (TICKET_ID) references AIRTICKETBOOKING_TICKET(ID)^
create index IDX_AIRTICKETBOOKING_ORDER_ON_PASSANGER on AIRTICKETBOOKING_ORDER (PASSANGER_ID)^
create index IDX_AIRTICKETBOOKING_ORDER_ON_TICKET on AIRTICKETBOOKING_ORDER (TICKET_ID)^
-- end AIRTICKETBOOKING_ORDER
-- begin AIRTICKETBOOKING_PASSANGER
create unique index IDX_AIRTICKETBOOKING_PASSANGER_UNIQ_PASSENGER_ID on AIRTICKETBOOKING_PASSANGER (PASSENGER_ID)^
create unique index IDX_AIRTICKETBOOKING_PASSANGER_UNIQ_EMAIL on AIRTICKETBOOKING_PASSANGER (EMAIL)^
-- end AIRTICKETBOOKING_PASSANGER
