alter table PHOTOSALON_ORDER_LINE add constraint FK_PHOTOSALON_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references PHOTOSALON_ORDER(ID);
alter table PHOTOSALON_ORDER_LINE add constraint FK_PHOTOSALON_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references PHOTOSALON_PRODUCT(ID);
create index IDX_PHOTOSALON_ORDER_LINE_ON_ORDER on PHOTOSALON_ORDER_LINE (ORDER_ID);
create index IDX_PHOTOSALON_ORDER_LINE_ON_PRODUCT on PHOTOSALON_ORDER_LINE (PRODUCT_ID);
